### ISSUE TITLE
React & Redux Resources

### ISSUE THREAD

**Issue by gaurav-gogia** [facebook-developer-circle-delhi/Community-Curated-Resources#10]
Requesting resources related to ReactJS, Redux & NextJS. Ideally, free project-based video tutorials of intermediate level or above. If someone could look into it & share related resources then please do. This would help a great deal.

Thanks!!

**Comment by saranshkataria** [comment]
The egghead course mentioned for Redux is great IMO. Rest I will let others add to the list

**Comment by gaurav-gogia** [comment]
I see, thanks!

**Comment by saranshkataria** [comment]
@DesmondANIMUS are the resources added sufficient enough?

**Comment by gaurav-gogia** [comment]
Yes, thanks 👍
