### ISSUE TITLE
Nothing Related to IOS Development

### ISSUE THREAD

**Issue by yash0707** [facebook-developer-circle-delhi/Community-Curated-Resources#37]

**Comment by saranshkataria** [comment]
@Aviral190694 some help here?

**Comment by Aviral190694** [comment]
@yash0707 @saranshkataria I will surely add some resources here for quick start by end of this week. Thank you for creating the issue @yash0707

**Comment by saranshkataria** [comment]
Some resources for iOS have been added, this issue can be closed now
