### ISSUE TITLE
No Resources related to Java

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [facebook-developer-circle-delhi/Community-Curated-Resources#44]
please add java resources 
and also prerequisites for android studio

**Comment by saranshkataria** [comment]
@ankit-kumar-dwivedi android studio resources can be found here: https://github.com/facebook-developer-circle-delhi/Community-Curated-Resources/blob/master/Android.md, will wait for someone to add Java ones

**Comment by saranshkataria** [comment]
Some resources have been added. If you think they are sufficient, feel free to close this out
