### ISSUE TITLE
Make Separate folders for separate resources

### ISSUE THREAD

**Issue by import-keshav** [facebook-developer-circle-delhi/Community-Curated-Resources#45]
like for linux , web development resources there should be separate folder

**Comment by saranshkataria** [comment]
Why do we need separate folders?

**Comment by import-keshav** [comment]
it will be looking nice and all  are files will not be look like a long list.

**Comment by saranshkataria** [comment]
Happy to have a PR from you if you think it can be arranged in a better manner.
